/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_bringardner_io_filesource_shell_NativeKeyboard */

#ifndef _Included_us_bringardner_io_filesource_shell_NativeKeyboard
#define _Included_us_bringardner_io_filesource_shell_NativeKeyboard

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_bringardner_io_filesource_shell_NativeKeyboard
 * Method:    getChar
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_us_bringardner_io_filesource_shell_NativeKeyboard_getChar (JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_us_bringardner_io_filesource_shell_NativeKeyboard_ready   (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
